### ISSUE TITLE
Make a function named compile()

### ISSUE THREAD

**Issue by yashpatel458** [clubgamma/Live-Code-Editor#4]
- link the html, css, and js ids to variables using document.getElementById()
- set the iframe id's contentWindow to a variable
- write a function that runs on document.body.keyup (when a key is pressed) that: - opens the textarea's contentWindow - writes the values of the html, css, and js variables in it
- closes the textarea's contentWindow

**Comment by Ankit1598** [comment]
Hey @yashpatel458 i would like to work on this can you assign it to me?

**Comment by Ankit1598** [comment]
Hey @yashpatel458 I have this code ready but I would like to make a new PR as I have also added an additional feature which stores the code on the browser so that when the user accidentally refreshes or the browser crashes he/she can continue from where they left it

**Comment by yashpatel458** [comment]
> Hey @yashpatel458 I have this code ready but I would like to make a new PR as I have also added an additional feature which stores the code on the browser so that when the user accidentally refreshes or the browser crashes he/she can continue from where they left it

Go For It!
